apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-example
  name: springboot-nodeport
spec:
  ports:
    - name: 8080-nodeport
      port: 8080
      protocol: TCP
  selector:
    app: springboot-example
  sessionAffinity: None
  type: NodePort
